### ISSUE TITLE
media.url READ ONLY

### ISSUE THREAD

**Issue by EvilEls** [oweitman/ioBroker.squeezeboxrpc#10]
`media.url` can be used to switch internet radio channels for example.
Please make it read+write by default.

**Comment by oweitman** [comment]
sorry for the delay, but i worked for 6 months abroad.

i have implemented a command dPlayUrl. please test.
if you find some errors please reopen the issue.
the cmdGeneral command allready exists to send any parameters to the LMS for the many other commands that are acually not implemented in the adapter
