### ISSUE TITLE
Artist in Favorite is not working right

### ISSUE THREAD

**Issue by Haifeif** [oweitman/ioBroker.squeezeboxrpc#101]
I use the Squeezboxrpc String widget, property set to 

Play widget: w00976 (my vis)
playerattribute: Artist

Looking at squeezeboxrpc.0.Players.squeezelite-5acb74.Artist, there is nothing visible

But the string widget on my VIS  shows for a frag of a second the correct(!) artist, but it disapears immediatly.

The same widget for RadioName & Title works great.

Versions:
 - Adapter version: 1.3.17
 - JS-Controller version: 6.0.11
 - Node version: v20.17.0
 - Operating system: LINUX

**Comment by Haifeif** [comment]
LMS shows the artist correct

**Comment by Haifeif** [comment]
If I use instead of the widget a standard string widget, the effect is the same!

**Comment by oweitman** [comment]
ich glaube wir können auf deutsch umschalten.
diesen issue bearbeiten wir erst, wenn wir die Anzeige der Daten in den Datenpunkten gerade gezogen haben.
Das einzige was das widget machtz, ist einfach nach der Auswahl des aktiven Players zu schauen und entsprechend umzuschalten.
Daher gehe ich davon aus, das es funktioniert, aber die Daten nicht richtig in die Datenpunkte geschrieben.
Wir sind ja im alpha release. da können wir dann in Ruhe testen. 
Weiter gehts im anderen Issue

**Comment by oweitman** [comment]
schau bitte auch mal diesen post an.
da habe ich eine präparierte mp3 datei hinterlegt, die alle möglichen tags (das sind die datenfelder in einer mp3) zum thema artist, band, etc belegt hat
https://forum.iobroker.net/topic/21809/test-support-adapter-squeezeboxrpc/285?_=1729889505730

für das streaming von internetsendern hilft das leider nicht

**Comment by Haifeif** [comment]
![image](https://github.com/user-attachments/assets/e6e8464c-c2dc-4145-ab2d-997f19f86216)
TPE2 MP3-Tag als Band
![image](https://github.com/user-attachments/assets/3c2b7734-5a0f-47d2-a106-efa3bc046ca1)

...als Interpret des Albums ...

**Comment by Haifeif** [comment]
Das mit dem Radio Tag kriegen wir hin! 😎

**Comment by Haifeif** [comment]
Ich wäre bereit, auf Dein Ehrenwort Dir meine Premium Spotify Sachen für die Testzeit zu übergeben.

**Comment by Haifeif** [comment]
Aber nicht über Github! 😁

**Comment by oweitman** [comment]
ja können wir so machen,
aber erst die lokale Musik fixen.

ich hör auch fast nur streaming.

da funktioniert das mit den Tags, soweit das von den Sendern bereitgestellt wird

bspw

https://i6.streams.ovh/sc/barazar1/stream

oder

http://opml.radiotime.com/Tune.ashx?id=s280322&formats=aac,ogg,mp3,hls&partnerId=16&serial=7325552091adb6773e2685820c9aa149

du kannst ja mal vorab diese stream bei dir mit spotify vergleichen

oder wenn du dich ein wenig mit den web developer tools auskennst im chrome oder edge, dann könnten da informationen auch schon reichen,

**Comment by oweitman** [comment]
Ich hab mal ein neues release bereitgestellt
[1.4.0-alpha.1](https://www.npmjs.com/package/iobroker.squeezeboxrpc/v/1.4.0-alpha.1)
bitte mal testen.
installierbar im iobroker über den katzenknopf / github / auswahl squeezeboxrpc

bei den text widgets hab ich etwas entdeckt, das die nicht immer zuverlässig funktioniert haben (bei produktiv immer, auf der testmaschine nicht immer)
ausserdem hab ich die behandlung für das tpe2 nochmal angepasst und besser dokumentiert.
der wo das problem hatte kann aber erst in 2 wochen test, evtl kannst da auch mal reinschauen.
evtl löst sich dadurch auch das streaming problem, ansonsten dann schauen wir im anschluss danach

**Comment by Haifeif** [comment]
Der Stream i6. bringt keine RadioNamen und kein ArtworkURL, der Stream opml. bringt ein Cover, aber keinen RadioName. 

Beide Streams setzen aber den LMS Namen als RadioNamen ein, womit ich leben kann. 
Oder war das die Funktion: Favoriten-Name = RadioName?

**Comment by oweitman** [comment]
> Das mit den Sender Logos geht noch nicht, aber etwas seltsames ist passiert: Beim ersten Wechsel auf Deinen Test Stream (i6) tauchte für eine Sekunde ein Logo auf

wie im anderen issue geschrieben, sind images im stream nicht enthalten.
ich vermute, das image war noch übrig von einem vorher angezeigten bild,
hast du den player noch zusätzlich gewechselt?

wie sieht die anzeige der daten für lokal gespeicherte musikstücke aus?
