### ISSUE TITLE
String Widget  don't show the Radio Name

### ISSUE THREAD

**Issue by Haifeif** [oweitman/ioBroker.squeezeboxrpc#103]
![image](https://github.com/user-attachments/assets/ee7590b4-9af0-4b43-b6be-58b596d94d47)

1 - vis properties of the string widget
2 - vis editor
3 - objects of squeezliterpc player
4 - vis at runtime (no radio name, no artist) 

**Versions:**  

Same as before 😉

**Comment by oweitman** [comment]
So, hier schauen wir nach Radio Name.
Ich gehe davon aus, das du einen Stream anhörst.
Kannst du mir die Stream URL nennen?
Ich muss schauen, welche Daten da vom LMS kommen.
Bitte auch prüfen, das im LMS das richtige angezeigt wird. Daten die im LMS nicht richtig vorhanden sind, können auch nicht nach iobroker transportiert werden.

**Comment by Haifeif** [comment]
Sorry, war anderweitig beschäftigt. 
Ja, ein Stream, er funktioniert einwandfrei
Die URL ist: http://streams.radiobob.de/rockoldies/aac-64/mediaplayer
LMS zeigt alles richtig an

**Comment by oweitman** [comment]
mit der alpha1 zeigt vis mir das auch an

![image](https://github.com/user-attachments/assets/cb5908c2-128c-40cd-94f4-44256625e559)
![image](https://github.com/user-attachments/assets/fa4a4a90-4eb3-42fb-b083-bcc7cb294ff9)

als radioname wird von lms wohl der name das favoriten übertragen

**Comment by oweitman** [comment]
fixed 1.4.0
