### ISSUE TITLE
[Question] How to choose from Spotify Playlists?

### ISSUE THREAD

**Issue by Haifeif** [oweitman/ioBroker.squeezeboxrpc#110]
How can I select a spotify playlist?

**Comment by oweitman** [comment]
das weiß ich nicht.
wie machst du das im LMS?

**Comment by Haifeif** [comment]
Klicken auf ->
Eigenen Anwendungen
  Spotty
    Wiedergabelisten

**Comment by oweitman** [comment]
ok, habe mal recherchiert.
generell muss das heute schon gehen
man benötigt aber die id der playlist, die sieht ungefähr so aus: 48wQfF1DX9xR2KY45plZ
so müsste dann im feld cmdGeneral im jeweiligen player der folgende eintrag (beispielhaft anhand der ID)
so aussehen.
`"play","spotify:playlist:48wQfF1DX9xR2KY45plZ"
`

evtl müsste ich ein paar experimente machen, daher würde ich auf das angebot eingehen,
mir temporär einen spotify zugang zur Verfügung zu stellen.

Die Zugangsdaten kannst du mir über die Chatfunktion im Forum unter meinem User OliverIO übermitteln
bzw wenn du Angaben von mir benötigst?
Was muss ich bei der Installation im LMS noch beachten? Werde auch die Gelegenheit nutzten, mal auf die aktuelle Version zu aktualisieren. Habe ich bisher noch nicht gemacht.

**Comment by Haifeif** [comment]
Sorry, war auf Reisen. Ich stelle die Informationen zusammen und melde mich, wenn ich alles habe. 
Vielen Dank für Dein Interesse!

**Comment by Haifeif** [comment]
Tut mir leid, aber kann ich Dir nicht eine eMail schicken? Ich habe nämlich keine Ahnung, was Du mit Chatfunktion im Forum meinst ...

😎

**Comment by Haifeif** [comment]
Ach so: Wenn Du mir im Issue Teil Deine Adresse schreibst, ist sie öffentlich. OK, keine gute Idee. Dann besser die Chatsache. Kannst Du mir asuf die Sprünge helfen?

**Comment by oweitman** [comment]
![image](https://github.com/user-attachments/assets/74796071-e5d5-4d9b-bf32-7dab268a4d39)

Wenn du im Forum auf mein Profil gehst, dann kannst du mir da eine Nachricht schreiben
![image](https://github.com/user-attachments/assets/2355d8d1-e903-41bc-ac78-0cffefdf7325)
Wenn man dann mal geschrieben hat, sieht man die Chats im Forum oben rechts mit der Sprechblase
![image](https://github.com/user-attachments/assets/15b4a96e-ed76-4c3e-afce-93714e57cb1b)

Was für Informationen brauchst du von mir?
Wie heißt du im Forum?

**Comment by Haifeif** [comment]
Noch immer sorry. Ich nutze im Moment nur Issues in Github, kein Forum. Welches Forum meinst Du bitte?

**Comment by oweitman** [comment]
Ok wusste ich nicht.
https://forum.iobroker.net/
Ich dachte jeder der den iobroker nutz hat da mal reingeschaut. Ich bin dort oliverIO

**Comment by oweitman** [comment]
hier aus dem forum ein hinweis
alle eigenen spotify playlists sind im lms unter wiedergabelisten gespeichert
jeder eintrag hat eine id
so kann man die id abrufen und dann über den adapter ansteuern.
![image](https://github.com/user-attachments/assets/bc330d32-9216-4c24-8be1-4169075c4e34)
evtl baue ich mal noch ein widget für die wiedergabelisten

um selbst die daten strukturiert abzurufen und für sich aufzubereiten habe ich einen sendto befehl eingefügt.
damit kann man im javascript adapter die informationen abrufen und selbst aufbereiten

detailbeschreibung ist im adapter readme enthalten

**Comment by oweitman** [comment]
In der neuen Version 1.5.0 ist ein playlist widget enthalten,
das alle Playlists anzeigt und abgespielt werden können
https://forum.iobroker.net/topic/21809/test-support-adapter-squeezeboxrpc/342?_=1732623935499
