### ISSUE TITLE
utilizes CPU to max

### ISSUE THREAD

**Issue by c-roe** [oweitman/ioBroker.squeezeboxrpc#18]
**Describe the bug**  
After connecting to LMS data is received but CPU gets utilized more and more until hardware freezes.

**To Reproduce**  
Install, maintain settings for LMS and start on ioBroker.

**Expected behavior**  
The CPU util. should stay on normal level.

**Screenshots & Logfiles**  
nope

**Versions:**  
 - Adapter version: 1.0.0
 - JS-Controller version: 2.2.9
 - Node version: 13.13.0
 - Operating system: Rasbian (Linux 4.19.97-v7l+ #1294 SMP Thu Jan 30 13:21:14 GMT 2020 armv7l GNU/Linux)
- LMS: 7.9.2 - 1575296326 (on other raspi with max2play)

**Additional context**  
When I browse the objects Favorites start flickering. I tried to change the Favorites interval and Telnet setting - not solving it.

I have 3 squeezelite devices. 2 are in sync.

Thanks a lot in advance - looking forward to use this adapter.

**Comment by oweitman** [comment]
Actually I have an issue the setstates in Iobroker =>3.0
After I fixed that, please upgrade to js comtroller >= 3 and retest.
Iobroker is actually untested with node>12

**Comment by c-roe** [comment]
I've downgraded to node 12.16 (stable) - same issue - but I am running iobroker 2.2.9. Do you mean <= 3.0?

issue with states seems to fit here - after installing and running for 5min a lot of states have to be removed.
![image](https://user-images.githubusercontent.com/64267865/80318852-457d1880-880d-11ea-9133-142352fcd904.png)

**Comment by oweitman** [comment]
ups 12000 states that seems the cause of the high cpu usage.
do you have many favorites? the number of states for each player is fixed.
the only variable number ist the number of favorites, saved in the LMS.

now you can retest. i fixed an issue caused by the new js-controller >= 3.0
others and me didnt have an issue with high cpu usage.
on my raspi 3b+ the adapter uses only 3% cpu (measured with top)

my actual configuration on the test-machine is:
raspberry 3b+ with raspian 10 buster
js-controller: 3.0.18
admin: 4.0.9
web: 3.0.2
socketio: 3.0.5

connected to
Logitech Media Server Version: 7.9.3 - 1582867832 @ Sat Feb 29 05:28:22 CET 2020
on a different server

if you want to see the actions of the adapter in detail you can switch the log level to silly.
but this produce many many log entries. each creation and setting of a state is reported.

**Comment by c-roe** [comment]
I have ~20 favorites - mostly streams. LMS is 7.9.2 (different server, too)

I will try with the new version the next days.

**Comment by oweitman** [comment]
please check what kind of states the adapter will create. normaly it shouldnt create so much states

**Comment by oweitman** [comment]
did you have the opportunity to test again

**Comment by c-roe** [comment]
thanks for the reminder

just tested it with the new stable js-controller@3.1.4 - same behavior - it created >8k states of favorites just in seconds

can I disable the favorite feature? dont need that at all

**Comment by oweitman** [comment]
a new version is in the iobroker latest repository available, there you can disable the favorites in the performance settings.

please can you provide some information about the created states, that i can fix or avoid such a problem.
is there a pattern in the creation of so many favorites? maybe you can provide me with the favorites.opml file from the lms server configuration for testing by myself.

**Comment by c-roe** [comment]
will check out the new version soon. here my favorites - replaced the private keys.

there are state dirs created like 7-dd-dd (d for digit) and in every dir the usual ones, I guess

[favorites.opml.txt](https://github.com/oweitman/ioBroker.squeezeboxrpc/files/4643106/favorites.opml.txt)

**Comment by c-roe** [comment]
installed 1.1.0 now - cant find the fav. setting in the perfomance tab

**Comment by c-roe** [comment]
![image](https://user-images.githubusercontent.com/64267865/82195956-5c3cf980-98f9-11ea-80ac-3c5ed1fd5eef.png)
have issues starting it

**Comment by oweitman** [comment]
> will check out the new version soon. here my favorites - replaced the private keys.
> 
> there are state dirs created like 7-dd-dd (d for digit) and in every dir the usual ones, I guess
> 
> [favorites.opml.txt](https://github.com/oweitman/ioBroker.squeezeboxrpc/files/4643106/favorites.opml.txt)

i checked the file. maybe the last line produce a circular reference
    <outline URL="http://www.mysqueezebox.com/public/opml/<private_key>/favorites.opml" icon="html/images/favorites.png" text="On mysqueezebox.com" />

**Comment by oweitman** [comment]
> ![image](https://user-images.githubusercontent.com/64267865/82195956-5c3cf980-98f9-11ea-80ac-3c5ed1fd5eef.png)
> have issues starting it

new version 1.2.1 is in produktion. after finish testing i publish it to the latest reporsitory

**Comment by oweitman** [comment]
> installed 1.1.0 now - cant find the fav. setting in the perfomance tab

if you dont find the setting, please change in iobroker the adapter tab to expert mode and click the upload icon on the right side of the squeezeboxrpc adapter row

**Comment by c-roe** [comment]
> 
> 
> > will check out the new version soon. here my favorites - replaced the private keys.
> > there are state dirs created like 7-dd-dd (d for digit) and in every dir the usual ones, I guess
> > [favorites.opml.txt](https://github.com/oweitman/ioBroker.squeezeboxrpc/files/4643106/favorites.opml.txt)
> 
> i checked the file. maybe the last line produce a circular reference
> `<outline URL="http://www.mysqueezebox.com/public/opml/<private_key>/favorites.opml" icon="html/images/favorites.png" text="On mysqueezebox.com" />`

removed it - will check with 1.2.1

**Comment by c-roe** [comment]
just saw that it is available - disabled the favs anyway - works like a charm

thanks a lot!

**Comment by oweitman** [comment]
With the Removed circular reference in your Favorites it should work aswell With enabled favaorites setting
