### ISSUE TITLE
ArtworkUrl: Image sometimes broken

### ISSUE THREAD

**Issue by r748** [oweitman/ioBroker.squeezeboxrpc#19]
Thanks for this nice adapter!

Some radio stations use placeholder/logo images, if there is no active title playing (e.g. during ads). Instead of a an URL, the variable "ArtworkUrl" then shows a link like e.g. `/imageproxy/http%3A%2F%2Fcdn-radiotime-logos.tunein.com%2Fs22491q.png/image.png`, which breaks the image widget. Rewriting the URL in this case to `http://cdn-radiotime-logos.tunein.com/s22491q.png` would fix the problem.

Reproducable with e.g. this stream `https://prod-34-83-53-134.wostreaming.net/sbsystems-wxdjfmaac-ib-64?session-id=8f2cf9dc2f8626d4c5cc1fb43025a93b`.

Cheers!
Rob

**Comment by oweitman** [comment]
you can change this behaviour in the settings of the LMS.
Settings->Advanced->Performance
Artwork Precahching = Dont precache
Artwork resize = Use Logitech servers to resize 

but anyway, i changed the adapter to also filter the imageproxy information and deliver the original url
Version 1.2.0 available in latest repository
please test and leave a test result as a comment, 
that i can move the adapter to the stable repository

**Comment by r748** [comment]
I didn't realize this can be changed server side... Thanks for also changing the adapter to solve this!

Unfortunately I can't test it, because version available in latest repository is 1.0.1. In stable repository, version is 1.0.0 btw.

**Comment by oweitman** [comment]
the information file for the latest repository ist normaly only updated twice a day by the iobroker team. 
you have to wait maybe till tomorrow.

**Comment by r748** [comment]
Ah, ok. Will let you know, thanks!

**Comment by r748** [comment]
Appears to work perfectly now, thanks for fixing!!
