### ISSUE TITLE
Error with Server discovery bind EADDRINUSE 0.0.0.0:3483

### ISSUE THREAD

**Issue by Strunzdesign** [oweitman/ioBroker.squeezeboxrpc#21]
Hi,

I have an entity of logitechmediaserver-bin running on my server. This is the same server that runs my ioBroker. If I install your adapter I get this error message in the logs of ioBroker:

squeezeboxrpc.0 | 2020-07-18 20:49:04.479 | error | (29753) Error with Server discovery bind EADDRINUSE 0.0.0.0:3483

I start the logitechmediaserver with these options: "--cliaddr 192.168.1.1 --httpaddr 192.168.1.1 --streamaddr 192.168.1.1 --playeraddr 192.168.1.1". The http port is at port 9002 to not to collide with ioBroker. Thus, I have logitechmediaserver using these bindings:

```
powerstation ~ # netstat -tulpen | grep perl
tcp        0      0 192.168.1.1:3483        0.0.0.0:*               LISTEN      114        1615069    28741/perl          
tcp        0      0 192.168.1.1:9090        0.0.0.0:*               LISTEN      114        1615070    28741/perl          
tcp        0      0 192.168.1.1:9002        0.0.0.0:*               LISTEN      114        1615072    28741/perl          
udp        0      0 0.0.0.0:47936           0.0.0.0:*                           114        1615073    28741/perl          
udp        0      0 192.168.1.1:3483        0.0.0.0:*                           114        1615068    28741/perl          
powerstation ~ # 
```

Thus, if your adaper tries to bind to "0.0.0.0:3483", this address is already in use.

Regards,
Florian

**Comment by oweitman** [comment]
which version of the plugin do you use? please use v1.2.1 from the latest repository.
or you can deactivate in the adapter settings / Performance settings the "search for other LMS servers"

i already request the port 3483 with the reuse option to listen on the server broadcasts. but on the same server this ist not working on all servers. in v1.2.1 i catch the error and deactivate the search for other servers automaticly

**Comment by Strunzdesign** [comment]
Hi, I was using version 1.2.1 from latest, the error occured once directly after adapter startup. Disabling the search helps, the error is gone now. Furthermore, how does your server implement UDP broadcasts? Neither logitechmediaserver nor this adapter create a UDP multicast listener that is visible via "ip maddr show". Not being a real multicast listener, is the re-use of a UDP port possible? This would require that the packets are multiplied on reception, which is a feature of multicasting, not of unicasts.

**Comment by oweitman** [comment]
the relevant line is here https://github.com/oweitman/ioBroker.squeezeboxrpc/blob/f4a1e73c879a15c44762e780d4db5cad9e7142b8/lib/iosbserver.js#L271
option reuseAddr and broadcast is set to true
if you have any advice, i would be grateful

**Comment by Strunzdesign** [comment]
Hi,

this is a bug in the slimserver. There, no "ReuseAddr" flag is set on the UDP socket. Furthermore, the "Broadcast" flag is missing, but I didn't test whether it is really required.

This fixes the issues with this adapter (after enabling "Search for other LMS-Server" again):

```
powerstation Networking # pwd
/opt/logitechmediaserver/Slim/Networking
powerstation Networking # diff -Naur UDP.pm~ UDP.pm
--- UDP.pm~     2019-12-02 15:18:46.000000000 +0100
+++ UDP.pm      2020-07-20 19:23:22.894311166 +0200
@@ -34,8 +34,9 @@
        $udpsock = IO::Socket::INET->new(
                Proto     => 'udp',
                LocalPort => SERVERPORT,
-               LocalAddr => $main::localClientNetAddr
-
+               LocalAddr => $main::localClientNetAddr,
+               Broadcast => 1,
+               ReuseAddr => 1
        ) or do {
 
                # XXX - exiting in a deep sub is kinda bad. should propagate up.
powerstation Networking # 
```

Time to open a bug report. I can do that, but at first, what do you think about this "solution"?

Regards,
Florian

**Comment by oweitman** [comment]
i am fine with this solution and that you open the bug report or pull request for the LMS.
please reference this issue, that i can see if and then michael herger fix this.

**Comment by Strunzdesign** [comment]
Ok done! Thanks for your support, the next version of LMS should incorporate that fix.

**Comment by oweitman** [comment]
I'm looking forward to the retest
