### ISSUE TITLE
Feature Request: Alexa Support

### ISSUE THREAD

**Issue by AlexanderSch90** [oweitman/ioBroker.squeezeboxrpc#22]
Hey, ich weiß nicht, ob dies möglich ist, aber mal ein Gedanke:
Hintergrund: Ich habe einen Echo-Dot in der Küche um mal schnell beim Kochen etc. per Sprachbefehl Musik an zu machen etc. So mache ich meinen Verstärker per Sprachbefehl an, an dem ein Raspi mit LMS-Client hängt. So kann ich Musik über die "gute Anlage" hören und der Alexa wird nur für den Befehl des "einschalten" missbraucht.

Idee: Cool wäre, wenn man sagen könnte: 
Alexa sage Musiksteuerung mach lauter oder Alexa sage Musiksteuerung spiele das Album Abbey Road oder Alexa sage Musiksteuerung hole die Musik vom Wohnzimmer

Somit hätte man Alexa nur für den Empfang der Sprachbefehle und nicht für die Ausgabe. 
Das Thema wird hier schon kostenpflichtig angeboten: https://www.squeezebox-forum.de/viewtopic.php?t=3937

Mich stört, dass man nochmal einen Skill+Abomodell braucht um die Verknüpfung zu realisieren.

Meine Idee: Iobroker weiß doch schon welche Alexas ich habe (Alexa2-Adapter) und auch welche Squeezeboxen ich nutze (dieser Adapter). Warum noch eine zusätzliche Ebene da reinbringen?!

Deshalb die Frage, könnte dieser Adapter dahingehend erweitert werden, dass dieser mit dem Alexa2-Adapter harmoniert?

Viele Grüße und danke für den Adapter!

**Comment by oweitman** [comment]
Das müsste eigentlich alles bereits über den iot Adapter machbar sein.
https://github.com/ioBroker/ioBroker.iot
zwar nicht out of the Box aber da man mit diesem Adapter über beliebige Sprachbefehle beliebige datenpunkte steuern kann müsste das umsetzbar sein.

https://github.com/ioBroker/ioBroker.iot

allerdings hast du auch hier sozusagen ein Abo-Modell, 
Für Alexa muss der Server-Endpunkt öffentlich im Internet erreichbar sein. Zwar könnte man zuhause am Router einen Port öffnen, das ist aus Sicherheitsgründen aber nicht ratsam. Daher ein Service nochmal dazwischen. Der iot-Dienst wird hier von den Iobroker Leuten angeboten.
