### ISSUE TITLE
Favorites url image broken

### ISSUE THREAD

**Issue by stratogk** [oweitman/ioBroker.squeezeboxrpc#23]
I get an incorrect image url from my favorites
![Χωρίς τίτλο](https://user-images.githubusercontent.com/43012620/103685887-9ea16c80-4f96-11eb-8a49-e92196b9000d.png)

ioBroker.squeezeboxrpc version 1.3.0

**Comment by oweitman** [comment]
ok, thank you for the advice. i fixed this already for the player artwork url.
but not for the favorites

**Comment by oweitman** [comment]
fixed in v1.3.3 on latest
