### ISSUE TITLE
Alarms

### ISSUE THREAD

**Issue by FNIO** [oweitman/ioBroker.squeezeboxrpc#24]
Ich vermisse den Eintrag "Alarms".
Laut Doku sollte dieser vorhanden sein.

**Comment by oweitman** [comment]
Welche Version nutzt du? Die Alarms-Funktion ist glaube ich erst ab 1.3.0 drin. Diese Version kannst du nutzten wenn du in iobroker auf das latest Repository umstellst.

**Comment by FNIO** [comment]
O.k.
Danke für den Hinweis...
nun ist ALARMS sichtbar.
