### ISSUE TITLE
nach JS-Controller upd 3.2.16 --> Warnings "has no existing object, this might lead to an error in future versions"

### ISSUE THREAD

**Issue by metaxa1** [oweitman/ioBroker.squeezeboxrpc#25]
Nach dem Update des Controllers auf 3.216 kommen regelmäßig Warnings beim Auslesen meiner 7 Favoriten vom LMS:
squeezeboxrpc.0 | 2021-03-04 11:19:36.959 | warn | (3272) State "squeezeboxrpc.0.Favorites.6.isaudio" has no existing object, this might lead to an error in future versions
-- | -- | -- | --
squeezeboxrpc.0 | 2021-03-04 11:19:36.958 | warn | (3272) State "squeezeboxrpc.0.Favorites.6.image" has no existing object, this might lead to an error in future versions
squeezeboxrpc.0 | 2021-03-04 11:19:36.958 | warn | (3272) State "squeezeboxrpc.0.Favorites.6.url" has no existing object, this might lead to an error in future versions
squeezeboxrpc.0 | 2021-03-04 11:19:36.958 | warn | (3272) State "squeezeboxrpc.0.Favorites.6.hasitems" has no existing object, this might lead to an error in future versions
squeezeboxrpc.0 | 2021-03-04 11:19:36.957 | warn | (3272) State "squeezeboxrpc.0.Favorites.6.id" has no existing object, this might lead to an error in future versions
squeezeboxrpc.0 | 2021-03-04 11:19:36.957 | warn | (3272) State "squeezeboxrpc.0.Favorites.6.Name" has no existing object, this might lead to an error in future versions
squeezeboxrpc.0 | 2021-03-04 11:19:36.956 | warn | (3272) State "squeezeboxrpc.0.Favorites.5.isaudio" has no existing object, this might lead to an error in future versions
squeezeboxrpc.0 | 2021-03-04 11:19:36.956 | warn | (3272) State "squeezeboxrpc.0.Favorites.5.image" has no existing object, this might lead to an error in future versions
squeezeboxrpc.0 | 2021-03-04 11:19:36.955 | warn | (3272) State "squeezeboxrpc.0.Favorites.5.url" has no existing object, this might lead to an error in future versions
squeezeboxrpc.0 | 2021-03-04 11:19:36.955 | warn | (3272) State "squeezeboxrpc.0.Favorites.5.hasitems" has no existing object, this might lead to an error in future versions
squeezeboxrpc.0 | 2021-03-04 11:19:36.954 | warn | (3272) State "squeezeboxrpc.0.Favorites.5.id" has no existing object, this might lead to an error in future versions
squeezeboxrpc.0 | 2021-03-04 11:19:36.954 | warn | (3272) State "squeezeboxrpc.0.Favorites.5.type" has no existing object, this might lead to an error in future versions
squeezeboxrpc.0 | 2021-03-04 11:19:36.953 | warn | (3272) State "squeezeboxrpc.0.Favorites.5.Name" has no existing object, this might lead to an error in future versions
squeezeboxrpc.0 | 2021-03-04 11:19:36.952 | warn | (3272) State "squeezeboxrpc.0.Favorites.4.isaudio" has no existing object, this might lead to an error in future versions
squeezeboxrpc.0 | 2021-03-04 11:19:36.951 | warn | (3272) State "squeezeboxrpc.0.Favorites.4.image" has no existing object, this might lead to an error in future versions
squeezeboxrpc.0 | 2021-03-04 11:19:36.950 | warn | (3272) State "squeezeboxrpc.0.Favorites.4.url" has no existing object, this might lead to an error in future versions
squeezeboxrpc.0 | 2021-03-04 11:19:36.949 | warn | (3272) State "squeezeboxrpc.0.Favorites.4.hasitems" has no existing object, this might lead to an error in future versions
squeezeboxrpc.0 | 2021-03-04 11:19:36.949 | warn | (3272) State "squeezeboxrpc.0.Favorites.4.id" has no existing object, this might lead to an error in future versions
squeezeboxrpc.0 | 2021-03-04 11:19:36.948 | warn | (3272) State "squeezeboxrpc.0.Favorites.4.type" has no existing object, this might lead to an error in future versions
squeezeboxrpc.0 | 2021-03-04 11:19:36.947 | warn | (3272) State "squeezeboxrpc.0.Favorites.4.Name" has no existing object, this might lead to an error in future versions
squeezeboxrpc.0 | 2021-03-04 11:19:36.945 | warn | (3272) State "squeezeboxrpc.0.Favorites.3.isaudio" has no existing object, this might lead to an error in future versions
squeezeboxrpc.0 | 2021-03-04 11:19:36.945 | warn | (3272) State "squeezeboxrpc.0.Favorites.3.image" has no existing object, this might lead to an error in future versions
squeezeboxrpc.0 | 2021-03-04 11:19:36.944 | warn | (3272) State "squeezeboxrpc.0.Favorites.3.url" has no existing object, this might lead to an error in future versions
squeezeboxrpc.0 | 2021-03-04 11:19:36.941 | warn | (3272) State "squeezeboxrpc.0.Favorites.3.hasitems" has no existing object, this might lead to an error in future versions
squeezeboxrpc.0 | 2021-03-04 11:19:36.940 | warn | (3272) State "squeezeboxrpc.0.Favorites.3.id" has no existing object, this might lead to an error in future versions
squeezeboxrpc.0 | 2021-03-04 11:19:36.940 | warn | (3272) State "squeezeboxrpc.0.Favorites.3.type" has no existing object, this might lead to an error in future versions
squeezeboxrpc.0 | 2021-03-04 11:19:36.939 | warn | (3272) State "squeezeboxrpc.0.Favorites.3.Name" has no existing object, this might lead to an error in future versions
squeezeboxrpc.0 | 2021-03-04 11:19:36.939 | warn | (3272) State "squeezeboxrpc.0.Favorites.2.isaudio" has no existing object, this might lead to an error in future versions
squeezeboxrpc.0 | 2021-03-04 11:19:36.938 | warn | (3272) State "squeezeboxrpc.0.Favorites.2.image" has no existing object, this might lead to an error in future versions
squeezeboxrpc.0 | 2021-03-04 11:19:36.938 | warn | (3272) State "squeezeboxrpc.0.Favorites.2.url" has no existing object, this might lead to an error in future versions
squeezeboxrpc.0 | 2021-03-04 11:19:36.937 | warn | (3272) State "squeezeboxrpc.0.Favorites.2.hasitems" has no existing object, this might lead to an error in future versions
squeezeboxrpc.0 | 2021-03-04 11:19:36.937 | warn | (3272) State "squeezeboxrpc.0.Favorites.2.id" has no existing object, this might lead to an error in future versions
squeezeboxrpc.0 | 2021-03-04 11:19:36.936 | warn | (3272) State "squeezeboxrpc.0.Favorites.2.type" has no existing object, this might lead to an error in future versions
squeezeboxrpc.0 | 2021-03-04 11:19:36.936 | warn | (3272) State "squeezeboxrpc.0.Favorites.2.Name" has no existing object, this might lead to an error in future versions
squeezeboxrpc.0 | 2021-03-04 11:19:36.935 | warn | (3272) State "squeezeboxrpc.0.Favorites.1.isaudio" has no existing object, this might lead to an error in future versions
squeezeboxrpc.0 | 2021-03-04 11:19:36.934 | warn | (3272) State "squeezeboxrpc.0.Favorites.1.image" has no existing object, this might lead to an error in future versions
squeezeboxrpc.0 | 2021-03-04 11:19:36.934 | warn | (3272) State "squeezeboxrpc.0.Favorites.1.url" has no existing object, this might lead to an error in future versions
squeezeboxrpc.0 | 2021-03-04 11:19:36.933 | warn | (3272) State "squeezeboxrpc.0.Favorites.1.hasitems" has no existing object, this might lead to an error in future versions
squeezeboxrpc.0 | 2021-03-04 11:19:36.933 | warn | (3272) State "squeezeboxrpc.0.Favorites.1.id" has no existing object, this might lead to an error in future versions
squeezeboxrpc.0 | 2021-03-04 11:19:36.932 | warn | (3272) State "squeezeboxrpc.0.Favorites.1.type" has no existing object, this might lead to an error in future versions
squeezeboxrpc.0 | 2021-03-04 11:19:36.931 | warn | (3272) State "squeezeboxrpc.0.Favorites.1.Name" has no existing object, this might lead to an error in future versions
squeezeboxrpc.0 | 2021-03-04 11:19:36.931 | warn | (3272) State "squeezeboxrpc.0.Favorites.0.isaudio" has no existing object, this might lead to an error in future versions
squeezeboxrpc.0 | 2021-03-04 11:19:36.930 | warn | (3272) State "squeezeboxrpc.0.Favorites.0.image" has no existing object, this might lead to an error in future versions
squeezeboxrpc.0 | 2021-03-04 11:19:36.930 | warn | (3272) State "squeezeboxrpc.0.Favorites.0.url" has no existing object, this might lead to an error in future versions
squeezeboxrpc.0 | 2021-03-04 11:19:36.929 | warn | (3272) State "squeezeboxrpc.0.Favorites.0.hasitems" has no existing object, this might lead to an error in future versions
squeezeboxrpc.0 | 2021-03-04 11:19:36.928 | warn | (3272) State "squeezeboxrpc.0.Favorites.0.id" has no existing object, this might lead to an error in future versions
squeezeboxrpc.0 | 2021-03-04 11:19:36.928 | warn | (3272) State "squeezeboxrpc.0.Favorites.0.type" has no existing object, this might lead to an error in future versions
squeezeboxrpc.0 | 2021-03-04 11:19:36.849 | warn | (3272) State "squeezeboxrpc.0.Favorites.0.Name" has no existing object, this might lead to an error in future versions

SqueezeboxRPC v1.3.3
JS-Controller v3.2.16
Node.js v12.19.0
NUC Linux VM

**Comment by oweitman** [comment]
Welche squeezeboxrpc Version hast du?

**Comment by metaxa1** [comment]
s.o.
SqueezeboxRPC v1.3.3
JS-Controller v3.2.16
Node.js v12.19.0
NUC Linux VM

**Comment by greatluis** [comment]
bei mir das selbe verhalten 

SqueezeboxRPC v1.3.3
JS-Controller v3.2.16
Node.js v12.20.0

**Comment by oweitman** [comment]
Problem ist identifiziert. Ich hatte den Adapter eigentlich letztes Jahr schon umgestellt,
aber die Favoriten vergessen mit anzupassen. Wird in den nächsten Tagen behoben.

**Comment by oweitman** [comment]
Version 1.3.4 ist nun verfügbar.
Darin sollte der Fehler behoben sein.
Bitte testen und über eine Rückmeldung wäre ich dankbar.

**Comment by metaxa1** [comment]
Herzlichen Dank, ich bekomme keine Warnings mehr. Perfekte und rasche Lösung, herzlichen Dank!
