### ISSUE TITLE
Control Favorites - Radio Stations - Rhasspy flow

### ISSUE THREAD

**Issue by kuumaur** [oweitman/ioBroker.squeezeboxrpc#29]
Thank you very much for your work.
I set up squeezeboxrpc in my iobroker.
No issues so far, i see all objects.
My question is about to control the Favorite Radio Stations.
I have some squeezelite Player in my house.
Currently, i am setting up a Rhasspy Voice assistant to control more thinks hands free by voice.
Case:
"Rhasspy please play radio station xyz in the kitchen."
The Intent is working, i just dont know how to script the squeezeboxrpc to play Favorite "3" on Player "Kitchen".

Do you have an idea?
Is it possible?

Br Kuumaur

**Comment by oweitman** [comment]
Yes it is possible.
Look in the documentation for
cmdPlayFavorite

**Comment by kuumaur** [comment]
Great, thanx a lot, it had worked for me.
