### ISSUE TITLE
 "squeezeboxrpc.0.Players.CCA_EssZimmer.Playlist" has no existing object, this might lead to an error in future versions

### ISSUE THREAD

**Issue by hsteinme** [oweitman/ioBroker.squeezeboxrpc#32]
- Instanz anhalten  
- Players Objekte löschen
- Instanz starten

Dann wird die Logdatei mit Warnings der folgenden Art überschüttet:
` "squeezeboxrpc.0.Players.CCA_EssZimmer.Playlist" has no existing object, this might lead to an error in future versions`

 - Adapter version: 1.3.4
 - JS-Controller version: 3.2.16
 - Node version: 12.18.4
 - Operating system: Linux RaspberryPi 5.4.51-v7l+ #1333 SMP Mon Aug 10 16:51:40 BST 2020 armv7l GNU/Linux

Siehe https://forum.iobroker.net/topic/42385/js-controller-3-2-jetzt-im-stable?page=1:
`Einige Adapter werden Warnungen ausgeben wenn State-Werte gesetzt werden VOR dem Anlegen von Objekten. `

**Comment by oweitman** [comment]
eigentlich sollte das schon seit letztem Jahr gefixt sein.
Erst kürzlich habe ich das erneut getestet, da ich bei Favorites es vergessen habe einzubauen.
Ich werde es nochmal testen.
Hattest du noch vis laufen, mit widgets, die auf die datenpunkte zugreifen wollten?

**Comment by hsteinme** [comment]
Nein, vis habe ich nicht im Einsatz. Ich habe auch bei meinem heutigen Test alle Skripte, die auf die fraglichen Objekte zugreifen könnten, angehalten. Die Warnungen traten dennoch auf.

Anbei ein Debug-Log:
[iobroker.2021-04-20.log.html.zip](https://github.com/oweitman/ioBroker.squeezeboxrpc/files/6344561/iobroker.2021-04-20.log.html.zip)

**Comment by oweitman** [comment]
ich habe mir das nun mal im Detail angeschaut.
Grundsätzlich ist, wie bereits geschrieben, eine Prüfung ob ein Datenpunkt existiert eingebaut.
Gemäß deiner Beschreibung konnte ich die Warnungen auch nachvollziehen, allerdings nur dann,
wenn ich nach dem Löschen relativ schnell wieder den Adapter gestartet habe.

Für mich stellt sich das so das:
Datenpunkte werden über die Oberfläche gelöscht.
Sie werden auch nicht mehr angezeigt.
Allerdings ist die Abarbeitung im Hintergrund durch iobroker noch nicht abgeschlossen.
Mein Adapter startet. Findet einen Teil der Datenpunkte  noch vor, da sie noch nicht gelöscht wurden
und macht nichts.
Dann kommt iobroker und löscht den Datenpunkt im Hintergrund und beim nächsten Schreiben des Datenpunkts durch
mich, ist der nicht mehr da und die Warnung entsteht.

Ich muss mal im Forum diskutieren, wie ich damit umgehen soll.
Eigentlich müsste ich vor jedem Schreibvorgang prüfen, ob es den DP gibt, falls nicht dann anlegen.
Da dieser Adapter allerdings sehr Kommunikationsintensiv ist und alle 750ms ca. 40 Datenpunkte multipliziert mit der Anzahl der Player geschrieben werden, fallen diese zusätzlichen Kommandos schon ins Gewicht.

Kannst du mal prüfen, was passiert, wenn du nach dem löschen ein paar Sekunden wartest? so 10-20 Sekunden?

**Comment by hsteinme** [comment]
Danke, Oliver, für Dein Kümmern. 

Unterhalb squeezeboxrpc.0.Players habe ich 5 Player. Ich nenne sie hier mal A, B, C, D und E. Vis ist nicht im Einsatz. Meine SqueezeBox-Skripten sind angehalten.

Hier meine Tests:

- Test #1
  - Instanz angehalten
  - Players Objektbaum gelöscht
  - sofort Instanz gestartet
  - Ergebnis
    - Player A: 1 x "no existing object"
	- Player B: 1 x "no existing object"
	- Player C: 28 x "no existing object"
	
- Test #2
  - Instanz angehalten
  - Players Objektbaum gelöscht
  - abgewartet bis Players im Browser gelöscht war
  - dann Instanz gestartet
  - Ergebnis
    - Player A: 1 x "no existing object"
	- Player C: 28 x "no existing object"
	
- Test #3
  - Instanz angehalten
  - Players Objektbaum gelöscht
  - abgewartet bis Players im Browser gelöscht war
  - zusätzlich 40 Sekunden gewartet
  - dann Instanz gestartet
  - Ergebnis
    - Player A: 1 x "no existing object"
	- Player C: 28 x "no existing object"	
	
Danach stellte ich fest, dass (auch nach Neustart des Browserfensters) nur die Player A, B, C angelegt waren, nicht jedoch D und E. (Ob derartiges bei den ersten beiden Testfällen auch aufgetreten ist, weiss ich nicht. Ich hatte nicht darauf geachtet.) Ich habe dann die Instanz angehalten und erneut gestartet. Danach waren alle Player sichtbar. In der Logdatei fanden sich dann 1 x "no existing object" für Player A und 1 x "no existing object" für Player C.

Adapter erneut gestartet. Und wieder in der Logdatei 1 x "no existing object" für Player A und 1 x "no existing object" für Player C.

Meine SqueezeBox.Skripten gestartet und genutzt. In der Logdatei stehen dann 1 x "no existing object" für Player D und 1 x "no existing object" für Player E.

Bei allen Playern mit "no existing object" ist dabei immer ein Datenpunkt squeezeboxrpc.0.Players.*.Playlist erwähnt, den ich im Objektbaum nicht sehen kann.

**Comment by hsteinme** [comment]
Eine kleine "Gegenrede" zu https://forum.iobroker.net/post/630635;

In vielen meiner eingesetzten Adapter gibt es Situationen, wo sich Objekte im Umfeld geändert haben, aber die entsprechenden Objekte im ioBroker nicht die Änderungen nachgezogen haben. "Beliebte" Beispiele: Umbenennungen und Löschungen von Objekten. In diesem Fall kann die Situation geheilt werden durch

- Anhalten des Adapters
- Löschen des entsprechenden Objektzweiges im Objekt-Reiter
- Neustart des Adapters

**Comment by hsteinme** [comment]
Wird eine neue Instanz des Adapters eingerichtet, so treten direkt danach die "no existing object" Warnungen ebenfalls en masse auf.

[NeueInstanz.zip](https://github.com/oweitman/ioBroker.squeezeboxrpc/files/6496588/NeueInstanz.zip)

**Comment by oweitman** [comment]
kannst du bitte mit der aktuellen version v1.3.6 in verbindung mit dem js-controller v3.3 nochmal neu testen?

**Comment by hsteinme** [comment]
Heute habe ich meinen ioBroker auf eine "moderne" js-controller Version hochgezogen und zwar auf 4.0.15. Unter der SqueezeboxRPC Adapter Version 1.3.9 treten die gschilderten Probleme weiterhin auf:

- beim Adapter-Restart nach dem Löschen der Objekte unterhalb Players
[20220226 State has no existing object.zip](https://github.com/oweitman/ioBroker.squeezeboxrpc/files/8147542/20220226.State.has.no.existing.object.zip)

- beim Erst-Start einer neuen Instanz
![20220226 Neue Instanz](https://user-images.githubusercontent.com/33778564/155859509-5e3d9eb2-70c1-4865-add1-aea0f7187fe4.jpg)

Bitte das Issue wieder öffnen.

**Comment by oweitman** [comment]
ja das ist der gleiche Fehler wie zuvor auch schon, der auch in dem von dir genannten Thread im Forum besprochen worden ist.
Das Problem tritt genau einmal auf, nämlich wenn eine neue Instanz angelegt und mit dem LMS verbunden wurde und wenn Datenpunkte gelöscht wurden und dann die Instanz gestartet wird.
Es kommt daher, das iobroker eine gewisse Zeit braucht um alle meine Anfragen zum anlegen eines Datenpunktes abzuarbeiten, ich aber gleich den LMS abfrage und dann auch die Datenpunkte aktualisieren will, zu denen es zu diesem Zeitpunkt wohl noch nicht alle Datenpunktobjekte angelegt wurden.
Dieses Problem tritt allerdings nur genau einmal auf, wenn ich
a) eine neue Instanz anlege und mit dem LMS verbinde
b) alle Datenpunkte lösche und dann die Instanz starte

bei jedem weiteren starten, tritt die Warnung nicht mehr auf.

Ich könnte nun das anlegen der Datenpunkte auf async/promises umstellen und abwarten bis alle promises erfüllt sind und dann erst mit dem abfragen starten. 
Ändert aber an der grundlegenden Funktion nix.
Mal schauen, wann ich das mache. 
Als nächstes muss der Adapter-Test auf github-Actions umgestellt werden, dann die Konfigurationsoberfläche auf React.

**Comment by hsteinme** [comment]
Danke, Oliver, für Deine ausführliche Erläuterung. Die betrachtete Situation ist ja derzeit als reine Warnung noch kein "richtiges Problem". Dennoch sollten wir die Androhung "this might lead to an error in future versions" ernst nehmen. Einige Breaking Changes der jüngeren Vergangenheit haben ja schmerzlich gezeigt, dass nicht jeder Entwickler seinen Hang zu Erziehungsmaßnahmen unterdrücken kann 😄

**Comment by oweitman** [comment]
Ja ist unschön, aber nach einmaligen Neustart des Adapters wäre auch das Problem weg.

**Comment by hsteinme** [comment]
Der Datenpunkt .Playlist wird in Javaskripten über den $-Selektor gefunden. Sein zugehöriges Objekt ist null. Er wird aber nicht im Objekte-Tab angezeigt. Was ist der Zweck einer derartigen Konstellation?

**Comment by oweitman** [comment]
wenn in den adapter einstellungen 
provide playlistinfos as JSON
angekreuzt wurden, dann stehen hier ein paar informationen zum weiterverarbeiten drin.

**Comment by oweitman** [comment]
Keine Reaktion mehr

**Comment by hsteinme** [comment]
(1) Reaktion auf was? Auf was wartest Du von mir?
(2) Habe ich denn einen Hinweis "Behoben mit ..." übersehen?

**Comment by oweitman** [comment]
hattest du diese Einstellung mal angekreuzt?
_wenn in den adapter einstellungen
provide playlistinfos as JSON
angekreuzt wurden, dann stehen hier ein paar Informationen zum weiterverarbeiten drin._
ich selbst kann es nicht nachvollziehen

**Comment by hsteinme** [comment]
Ja, wenn diese Option aktiviert ist, dann ist der Datenpunkt im Objektbaum zu sehen, wobei er bei manchen Playern gefüllt ist.

**Comment by oweitman** [comment]
dann ist ja alles gut.
oder was ist das konkrete Problem noch?
Der Datenpunkt existiert,
er ist in der Doku beschrieben
er wird halt nur gefüllt wenn die Option angekreuzt ist?

**Comment by hsteinme** [comment]
👍
