### ISSUE TITLE
Warnmeldungen nach dem Update auf js-controller 3.3.4.

### ISSUE THREAD

**Issue by mane444** [oweitman/ioBroker.squeezeboxrpc#37]
Nach dem Update auf den js-controller 3.3.4 kommen Warnmeldungen über falsche Datentypen.

<html>
<body>

squeezeboxrpc.0 | 2021-05-12 07:01:05.017 | info | (2148) State value to set for "squeezeboxrpc.0.Favorites.0-8.url" has to be type "number" but received type "string"
-- | -- | -- | --
squeezeboxrpc.0 | 2021-05-12 07:01:05.016 | info | (2148) State value to set for "squeezeboxrpc.0.Favorites.0-8.hasitems" has to be type "string" but received type "number"
squeezeboxrpc.0 | 2021-05-12 07:01:05.016 | info | (2148) State value to set for "squeezeboxrpc.0.Favorites.0-7.url" has to be type "number" but received type "string"
squeezeboxrpc.0 | 2021-05-12 07:01:05.015 | info | (2148) State value to set for "squeezeboxrpc.0.Favorites.0-7.hasitems" has to be type "string" but received type "number"
squeezeboxrpc.0 | 2021-05-12 07:01:05.014 | info | (2148) State value to set for "squeezeboxrpc.0.Favorites.0-6.url" has to be type "number" but received type "string"
squeezeboxrpc.0 | 2021-05-12 07:01:05.013 | info | (2148) State value to set for "squeezeboxrpc.0.Favorites.0-6.hasitems" has to be type "string" but received type "number"
squeezeboxrpc.0 | 2021-05-12 07:01:05.012 | info | (2148) State value to set for "squeezeboxrpc.0.Favorites.0-5.url" has to be type "number" but received type "string"
squeezeboxrpc.0 | 2021-05-12 07:01:05.009 | info | (2148) State value to set for "squeezeboxrpc.0.Favorites.0-5.hasitems" has to be type "string" but received type "number"
squeezeboxrpc.0 | 2021-05-12 07:01:05.008 | info | (2148) State value to set for "squeezeboxrpc.0.Favorites.0-4.url" has to be type "number" but received type "string"
squeezeboxrpc.0 | 2021-05-12 07:01:05.007 | info | (2148) State value to set for "squeezeboxrpc.0.Favorites.0-4.hasitems" has to be type "string" but received type "number"
squeezeboxrpc.0 | 2021-05-12 07:01:05.006 | info | (2148) State value to set for "squeezeboxrpc.0.Favorites.0-3.url" has to be type "number" but received type "string"
squeezeboxrpc.0 | 2021-05-12 07:01:05.006 | info | (2148) State value to set for "squeezeboxrpc.0.Favorites.0-3.hasitems" has to be type "string" but received type "number"
squeezeboxrpc.0 | 2021-05-12 07:01:05.005 | info | (2148) State value to set for "squeezeboxrpc.0.Favorites.0-2.url" has to be type "number" but received type "string"
squeezeboxrpc.0 | 2021-05-12 07:01:05.005 | info | (2148) State value to set for "squeezeboxrpc.0.Favorites.0-2.hasitems" has to be type "string" but received type "number"
squeezeboxrpc.0 | 2021-05-12 07:01:05.004 | info | (2148) State value to set for "squeezeboxrpc.0.Favorites.0-1.url" has to be type "number" but received type "string"
squeezeboxrpc.0 | 2021-05-12 07:01:05.003 | info | (2148) State value to set for "squeezeboxrpc.0.Favorites.0-1.hasitems" has to be type "string" but received type "number"
squeezeboxrpc.0 | 2021-05-12 07:01:05.002 | info | (2148) State value to set for "squeezeboxrpc.0.Favorites.0-0.url" has to be type "number" but received type "string"
squeezeboxrpc.0 | 2021-05-12 07:01:05.000 | info | (2148) State value to set for "squeezeboxrpc.0.Favorites.0-0.hasitems" has to be type "string" but received type "number"
squeezeboxrpc.0 | 2021-05-12 07:01:04.857 | info | (2148) State value to set for "squeezeboxrpc.0.Favorites.7.url" has to be type "number" but received type "string"

</body>
</html>

**Comment by oweitman** [comment]
fixed in v1.3.6
