### ISSUE TITLE
Wrong type fpr JS-Controller 3.3

### ISSUE THREAD

**Issue by metaxa1** [oweitman/ioBroker.squeezeboxrpc#38]
`squeezeboxrpc.0	2021-08-05 21:47:06.916	info	(19018) State value to set for "squeezeboxrpc.0.Server.LastScan" has to be type "number" but received type "string"`

**Comment by oweitman** [comment]
fixed in v1.3.5

**Comment by oweitman** [comment]
oh moment, must check again

**Comment by oweitman** [comment]
ok, now fixed in v1.3.6
