### ISSUE TITLE
which datapoint to "play" and "pause" a file

### ISSUE THREAD

**Issue by Goeste** [oweitman/ioBroker.squeezeboxrpc#49]
Hi @oweitman,

What datapoint do I need to use to play a file and to pause a file? I can't seem to find the correct datapoint.

Best, goeste

**Comment by oweitman** [comment]
the datapoint ist

<html>
<body>


cmdPlayUrl | to play a url | example "http://50.7.77.114:8101/;"
-- | -- | --

</body>
</html>
can also be a path/filename, but the file should be accessible by the LMS

and

<html>
<body>


state | R/W | get/set play state: pause(0),play(1),stop(2)
-- | -- | --



</body>
</html>

please see the documentation
https://github.com/oweitman/ioBroker.squeezeboxrpc

**Comment by Goeste** [comment]
many thanks for the hint. therefore an additional datapoint is needed in iobroker. At leaste this is how I got it properly working :)

THX!

Best, goeste
