### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by EvilEls** [oweitman/ioBroker.squeezeboxrpc#56]
Hi,
would it be possible to set the `sleep` timer with the adapter?
Thanks!

**Comment by oweitman** [comment]
yes,
you can write 
`sleep 10 `
in the player datapoint cmdGeneral to set the sleeptime to 10 seconds

**Comment by EvilEls** [comment]
Great! Thank you!
I wasn't aware that 
```cmdGeneral        | a general command field to send commands to the player. every field must enclosed by quotation marks. parameters musst be seperated by comma. Example: "play","1"``` 
means, that I can send any API command 😀

According to the API docs I assume, that `Sleep at end of song` is not supported.

**Comment by oweitman** [comment]
not all commands have been tested, but yes, i think you can. if you have any problems, just open an issue here.
sleep at the end of a song is not directly supported, but when the playlist ends, the LMS will stop playing. another alternative would be to monitor the duration of a song in iobroker and then stop it in time and maybe even slowly lower the volume.

**Comment by EvilEls** [comment]
Not a beauty, but it works :)

![grafik](https://user-images.githubusercontent.com/29343914/155228336-3a938143-cb98-4bb5-b4b6-b46a4b6e03b9.png)

Thanks for the hint!

**Comment by oweitman** [comment]
If you want you can report it here
https://forum.iobroker.net/post/253674
to give something back to the community.
Not many read the GitHub issues
