### ISSUE TITLE
Adapter verbindet sich nicht mit Proxmox LXC Container

### ISSUE THREAD

**Issue by Stevelande** [oweitman/ioBroker.squeezeboxrpc#64]
Ich habe gesehen das hier auch in meiner Muttersprache kommuniziert wird.
Ich habe einen Proxmox Server laufen. Dort ist iobroker und LMS als LXC Container installiert und LMS als VM.
Der Adapter möchte sich aber nicht mit dem LMS LXC Container verbinden mit der VM hingegen schon. Ich habe den Adapter auch schon auf debug gestellt um mehr Informationen zu bekommen. das Log sagt `

queezeboxrpc.0 | 2022-07-01 21:16:10.852 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
-- | -- | -- | --
squeezeboxrpc.0 | 2022-07-01 21:16:10.852 | info | terminating
squeezeboxrpc.0 | 2022-07-01 21:16:10.852 | info | squeezeboxrpc unloaded
squeezeboxrpc.0 | 2022-07-01 21:16:10.849 | error | Cannot read property 'hasOwnProperty' of undefined
squeezeboxrpc.0 | 2022-07-01 21:16:10.848 | error | TypeError: Cannot read property 'hasOwnProperty' of undefined at ioSBPlayer.doPlayerUpdateStatus (/opt/iobroker/node_modules/iobroker.squeezeboxrpc/lib/iosbplayer.js:539:28) at IoSbServer.<anonymous> (/opt/iobroker/node_modules/iobroker.squeezeboxrpc/lib/iosbserver.js:659:31) at handle (/opt/iobroker/node_modules/squeezenode-oweitman/squeezerequest.js:62:13) at /opt/iobroker/node_modules/squeezenode-oweitman/squeezerequest.js:164:13 at ClientHttp.Client._parseResponse (/opt/iobroker/node_modules/jayson/lib/client/index.js:219:10) at /opt/iobroker/node_modules/jayson/lib/client/index.js:150:10 at Object.Utils.JSON.parse (/opt/iobroker/node_modules/jayson/lib/utils.js:266:3) at IncomingMessage.<anonymous> (/opt/iobroker/node_modules/jayson/lib/client/http.js:86:22) at IncomingMessage.emit (events.js:412:35) at endReadableNT (internal/streams/readable.js:1333:12)
squeezeboxrpc.0 | 2022-07-01 21:16:10.848 | error | uncaught exception: Cannot read property 'hasOwnProperty' of undefined
squeezeboxrpc.0 | 2022-07-01 21:16:10.369 | info | starting. Version 1.3.9 in /opt/iobroker/node_modules/iobroker.squeezeboxrpc, node: v14.19.3, js-controller: 4.0.23
squeezeboxrpc.0 | 2022-07-01 21:16:10.369 | info | starting. Version 1.3.9 in /opt/iobroker/node_modules/iobroker.squeezeboxrpc, node: v14.19.3, js-controller: 4.0.23
squeezeboxrpc.0 | 2022-07-01 21:16:06.760 | info | Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
squeezeboxrpc.0 | 2022-07-01 21:16:06.760 | info | terminating
squeezeboxrpc.0 | 2022-07-01 21:16:06.759 | info | squeezeboxrpc unloaded
squeezeboxrpc.0 | 2022-07-01 21:16:06.759 | info | Got terminate signal TERMINATE_YOURSELF

`
![Bildschirmfoto vom 2022-06-30 17-34-03](https://user-images.githubusercontent.com/26803698/176956646-0bffa113-0600-4352-bfa3-c43ffcf3b207.png)
und so sieht es im iobroker aus. 
Kannst du hier weiterhelfen?

**Comment by oweitman** [comment]
Wir hatten ja bereits im Forum kommuniziert
