### ISSUE TITLE
Artist missing after 1.3.10 update using Spotty Plugin

### ISSUE THREAD

**Issue by MAR-L3Y** [oweitman/ioBroker.squeezeboxrpc#72]
Hello ,

i just discovered that the DP for Artist is empty when i use version 1.3.10
I tried to put on the right settings in LMS but i can't find the right option to  get this working again.
on version 1.3.9 there is no problem at all.
I'm using The LMS and Squeezeboxes only with the Spotty plugin but can't find a option for changing the TPE there. 
The other DPs are filled like they should be just the Artist is missing.
Is it possible to make the TPE2/TPE3 feature that got in with version 1.3.10 selectable in a future version?

**Comment by oweitman** [comment]
this is difficult.
2 weeks ago i created a mp3 file with all relevant tags
ALBUMARTIST
COMPOSER
CONDUCTOR
DIRECTOR
ORIGARTIST

and look into the LMS-source code, that is not so easy.
but now i have a little clue that lms is doing with the mp3 tags
and how the tpe2/3 option changes the output of the fields

next i want to introduce some more datapoints
ALBUMARTIST
TRACKARTIST
COMPOSER
CONDUCTOR
BAND

These are the fields that LMS ist sending for a track (but not allways all of them)
LMS dont send the DIRECTOR-field
The Artist-Datapoint changes it behavior to a calculated datapoint based on the tpe-option

with this changes we try and i need response from the community for more differences.

**Comment by oweitman** [comment]
can you please check this post
https://forum.iobroker.net/topic/21809/test-support-adapter-squeezeboxrpc/286?_=1723119130833

**Comment by oweitman** [comment]
and finaly please check the test release 1.4.0-alpha
for testing you have to install it from github via the github button in iobroker

**Comment by oweitman** [comment]
should be fixed 1.4.0
