### ISSUE TITLE
Widget Problem

### ISSUE THREAD

**Issue by Wox1** [oweitman/ioBroker.squeezeboxrpc#8]
Hello,

I have installed your Adapter. Then in VIS-Edit i edit the "Player" Widget.
But i can not see anything!?
Under instance i edit: "squeezeboxrpc.0"
But i can see nothing only the clear frame.
When i change the instance to "squeezeboxrpc.0.Players" nothing change.

What is the Problem?

What Value must i right in "Anzeige Index" this is empty

Sincerely

**Comment by oweitman** [comment]
Hi, can you see in the object view of the iobroker below the squeezeboxrpc.0.Player node any child- nodes? if yes: which browser and version do you use?

**Comment by Wox1** [comment]
Hello,

Yes i can see the Player Node and all my Players with the right name.
I use Google Chrome Version 76.0.3809.100.
Are you German?

Sincerely

**Comment by paddybo93** [comment]
Hello,
i have the same problem. I tried different Browser, Firefox, Chrome and Internet Explorer. I tried to reinstall the squeezeboxrpc adapter but I still have the problem. I can't see the widget. 
Is there already any solution?

Best regards
Paddy

**Comment by oweitman** [comment]
sorry for the delay, i worked abroad for the last 6 months with littel time and access to my systems.
pleas can you provide a browser log?
steps for chrome are
1) open new tab
2) press ctrl + shift + i (this opens the developer tools)
3) reload the page with your widgets
4) copy the log from the console section in the developer tools

ps: yes i am german

**Comment by oweitman** [comment]
ok. i found something. due to some changes in the iobroker.controller 2.0 a used api left.
i changed it and now it must work again. please update the adapter and test. 
if everything is fine for you please close this issue .

**Comment by paddybo93** [comment]
Yes, it works ✌
