### ISSUE TITLE
Log Spam

### ISSUE THREAD

**Issue by EvilEls** [oweitman/ioBroker.squeezeboxrpc#9]
The adapter is spamming the log with debug messages.
Please make an option to turn it off.

**Comment by oweitman** [comment]
sorry for the delay, i worked for 6 months abroad.
do you found the adapter settings ther is a tab for the debug settings.
in this tab you can enable/disable the level of debug messages.
all these settings have effect on the log-file written on server and the log.tab in iobroker admin

all events generated in the event-tab are created by iobroker and the adapter can not control or filter it.
