### ISSUE TITLE
Anzeige Index der Favoriten Knopfleiste lässt sich nicht ändern

### ISSUE THREAD

**Issue by Haifeif** [oweitman/ioBroker.squeezeboxrpc#98]
Sobald ich eine Zahl ändere, werden die Werte eigenständig verändert.

Zustand vor Änderung:
![image](https://github.com/user-attachments/assets/f2406940-39d9-41fb-b1ab-9a1d5aa38c21)

Jetzt versuche ich, 0.0.1 in 2.0 zu ändern. Dazu markiere ich die führende 0 und tippe eine 2 ein.
Sobald ich die 2 eingetippt habe und sie im Feld auch kurz zu sehen ist, verschwindet die Eingabe und das Feld sieht so aus:

![image](https://github.com/user-attachments/assets/af8db1ba-ff51-4e49-86d6-796ff3a1a55e)
Die 0.0.1 wurde durch eine 0 ersetzt, die eingegebene 2 ist auch weg.

Der einzige Weg, der bei mir funktioniert hat: Feldinhalt kopieren, mit Notepad++ editieren und dann zurück einfügen.

**Version:**  
 - Adapter version: v1.3.15
 - JS-Controller version: 6.0.11
 - Node version: v20.17.0
 - Operating system: LINUX

**Comment by oweitman** [comment]
ja das ist korrekt.
leider hat vis da so einen autoaktualisierungsfunktion.
sobald vis erkennt, das so eine einstellung verändert wurde, ruft er automatisch die widget funktion auf.
das lässt sich so leider nicht abstellen.
bei komplexen änderungen ist es so wie du bereits herausgefunden hast die beste methode das anzupassen.
also kopieren und in einem externen editor anpassen und dann auf einen schlag reinkopieren

**Comment by oweitman** [comment]
in v1.3.17 habe ich noch einen edit knopf angefügt der einen dialog öffnen.
in diesem kann man in ruhe editieren.

**Comment by Haifeif** [comment]
Klasse, danke schön. Ich habe bisher immer nur "offizielle" Adapter verwendet, daher habe ich keine Erfahrung mit Github Adaptern. Anyway, ich habe die Katze in ioBroker benutzt, und installiert wurde Deine 1.4.0 alpha. Die habe ich schnell wieder gelöscht, und versuche jetzt, die 1.3.17 zu installieren. Das verweigert er mit der Meldung

iobroker Cannot install from GitHub. Invalid URL https://github.com/oweitman/ioBroker.squeezeboxrpc/releases/tag/v1.3.17

Was mache ich falsch?

PS: Der Knopf funktioniert!

**Comment by oweitman** [comment]
Die v1.3.17 ist ganz normal über das Beta repo verfügbar
Also einfach im iobroker über die Einstellung, auf das Beta repo umstellen und nur diesen Adapter aktualisieren. Danach wieder auf stable zurückstellen.
Die Alpha Version enthält eine Anpassung, die jemand anders testen sollte. Hier weiß ich noch nicht, ob es so funktioniert, wie es soll. Daher ist diese nicht im Beta Repository gelandet.
da geht es darum, wie es unter einer bestimmten Einstellung der Interpret angezeigt werden soll.

**Comment by Haifeif** [comment]
Alles klar, funktioniert. Sorry für meine Unkenntnis. Ich arbeite jetzt mal weiter, habe schon eine Liste angefangen mit "nice to have" Punkten.
